### PR TITLE
Revert Apache2.0

### PR DESCRIPTION
**Pull request by heyanlong**
The project files are all apache2.0 License, but the project is GPLv3 License, too confusing.

### CODE REVIEW

**Comment by heiyeluren** [comment]
@heyanlong 为啥要换成GLP v3协议呀？Apache V2 不是更合适么？原因是啥？麻烦介绍一下

**Comment by heyanlong** [comment]
Maybe you should to review this PR.

**Comment by heyanlong** [comment]
This commit is to restore the license to Apache 2.0.

**Comment by qbhy** [comment]
围观 ~

**Comment by heiyeluren** [comment]
已经把协议更新了~ 谢谢啦

**Pull request closed without merging**
